### ISSUE TITLE
为什么我提取的视频部分没有声音呢？

### ISSUE THREAD

**Issue by balala8** [youfantan/N0vaResourceExtractor#2]
你好，具体表现是讲故事和跳舞的视频有声音，但是有部分视频音画不同步。
一些基础视频（坐摇椅上戴耳机等）没有声音，请问这是为啥呢？

**Comment by youfantan** [comment]
鹿鸣跳舞的视频是没有声音的，声音也存储到ndf文件里，是mp3文件流。

**Comment by balala8** [comment]
好的。我知道了。感谢你的项目。在你的项目上，我做了鹿鸣的 mac 版。
