### ISSUE TITLE
Linux version was not useless!

### ISSUE THREAD

**Issue by 641i130** [youfantan/N0vaResourceExtractor#3]
> remove useless Linux version

I would've used it :eyes: 
Could you include build instructions for Linux users too?

**Comment by youfantan** [comment]
N0vaDesktop not supported Linux yet.It only supports Android and Windows so I won't build another Linux version.
For special needs please use release 1.0 and if you want to build a version for linux,just comment`GetPrivileges()` and remove the manifest in CMakeList.txt.

**Comment by 641i130** [comment]
Fair enough. I did get it to install on linux through wine, which lets me download the files (just doesn't play them properly, that's why I needed a way to extract).
Thanks for the cool project!
